### ISSUE TITLE
查询返回值中的score值不在0-1区间

### ISSUE THREAD

**Issue by spirit832** [vearch/vearch-python#10]
通过pythonSDK测试，表空间索引类型为     
 "engine" : {
         "index_size": 100000,
         "retrieval_type": "FLAT"
     }
插入数据后执行查询（指定查询向量，过滤条件，暴力搜索，返回条数）
query = {}
query["vector"] = [{"field": "feature", "feature": features}]
query["filter"] = [{"term": {"row_info": ['20212', '20213'], "operator": "or"}}]
query["topn"] = 4
query["is_brute_search"] = 1
query["retrieval_param"]= {"metric_type": "InnerProduct"}
查询结果的score不在0-1区间，还有负值。
想咨询一下，score不是代表的余弦相似度吗

**Comment by zcdb** [comment]
InnerProduct是指的内积，暂时是没有支持余弦相似度，实际上将向量归一化之后内积就等效于余弦相似度了

**Comment by spirit832** [comment]
了解了
